name: Playwright E2E
on: [pull_request]

permissions:
  contents: read

jobs:
  playwright:
    name: QuickPizza browser test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22

      - name: Build Binary
        run: make build

      - name: Start Server
        run: ./bin/quickpizza &

      - name: Install Playwright browser
        run: cd pkg/web && npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: cd pkg/web && npm run test:e2e
